### ISSUE TITLE
Doesn't work anymore with V41

### ISSUE THREAD

**Issue by sadokx** [ScottSavarie/Clipboard-Fill#7]
When running the plugin, it just switches the fill to an empty image. 

PS. Thanks for the great work that went into this! It's a time saver!

![image](https://cloud.githubusercontent.com/assets/12555077/20286656/89db520a-aa8d-11e6-9ea7-ada61006ae28.png)

**Comment by ScottSavarie** [comment]
Hey @sadokx I can't reproduce this. For me, the image fill still switches but in the Inspector the change isn't reflected until you click on the fill or reveal the UI from your screenshot. Do you maybe have any other Plugins with the same hot key or something? Also have you updated to the latest version? I updated the plugin a few weeks ago for Sketch 40.

**Comment by sadokx** [comment]
Thanks for the reply @ScottSavarie. I did update because I saw the plugin stopped working for V40, but the problem started in V41.

However, I dont know why, I closed Sketch, cleaned cache, and now it works (?).

Anyway, thanks for keeping an eye on this and for your work! It's one of my favorite plugins, if not the most useful. Thanks!
